# Accuracy Message

std_msgs/Float32[] pNEDError
std_msgs/Float32[] vNEDError
std_msgs/Float32 rollError
std_msgs/Float32 pitchError
std_msgs/Float32 headingError
std_msgs/Float32 ellipsoidSemiMajorError
std_msgs/Float32 ellipsoidSemiMinorError
std_msgs/Float32 ellipsoidOrientationError



#  struct Accuracy {
#    pNEDError @0 :List(Float32);
#    vNEDError @1 :List(Float32);
#    rollError @2 :Float32;
#    pitchError @3 :Float32;
#    headingError @4 :Float32;
#    ellipsoidSemiMajorError @5 :Float32;
#    ellipsoidSemiMinorError @6 :Float32;
#    ellipsoidOrientationError @7 :Float32;
#  }
