# Address Message

std_msgs/String title
std_msgs/Float64 lat
std_msgs/Float64 lng
std_msgs/String house
std_msgs/String address
std_msgs/String street
std_msgs/String city
std_msgs/String state
std_msgs/String country



#  struct Address {
#    title @0 :Text;
#    lat @1 :Float64;
#    lng @2 :Float64;
#    house @3 :Text;
#    address @4 :Text;
#    street @5 :Text;
#    city @6 :Text;
#    state @7 :Text;
#    country @8 :Text;
#  }
