# AndroidBuildInfo Message

std_msgs/String board
std_msgs/String bootloader
std_msgs/String brand
std_msgs/String device
std_msgs/String display
std_msgs/String fingerprint
std_msgs/String hardware
std_msgs/String host
std_msgs/String id
std_msgs/String manufacturer
std_msgs/String model
std_msgs/String product
std_msgs/String radioVersion
std_msgs/String serial
std_msgs/String[] supportedAbis
std_msgs/String tags
std_msgs/Int64 time
std_msgs/String type
std_msgs/String user

std_msgs/String versionCodename
std_msgs/String versionRelease
std_msgs/Int32 versionSdk
std_msgs/String versionSecurityPatch
