# AndroidCaptureResult Message

std_msgs/Int32 sensitivity
std_msgs/Int64 frameDuration
std_msgs/Int64 exposureTime
std_msgs/UInt64 rollingShutterSkew
std_msgs/Int32[] colorCorrectionTransform
std_msgs/Float32[] colorCorrectionGains
std_msgs/Int8 displayRotation



#  struct AndroidCaptureResult {
#    sensitivity @0 :Int32;
#    frameDuration @1 :Int64;
#    exposureTime @2 :Int64;
#    rollingShutterSkew @3 :UInt64;
#    colorCorrectionTransform @4 :List(Int32);
#    colorCorrectionGains @5 :List(Float32);
#    displayRotation @6 :Int8;
#  }
