# AndroidBuildInfo Message

std_msgs/String board
std_msgs/String bootloader
std_msgs/String brand
std_msgs/String device
std_msgs/String display
std_msgs/String fingerprint
std_msgs/String hardware
std_msgs/String host
std_msgs/String id
std_msgs/String manufacturer
std_msgs/String model
std_msgs/String product
std_msgs/String radioVersion
std_msgs/String serial
std_msgs/String[] supportedAbis
std_msgs/String tags
std_msgs/Int64 time
std_msgs/String type
std_msgs/String user

std_msgs/String versionCodename
std_msgs/String versionRelease
std_msgs/Int32 versionSdk
std_msgs/String versionSecurityPatch



#  struct AndroidBuildInfo {
#    board @0 :Text;
#    bootloader @1 :Text;
#    brand @2 :Text;
#    device @3 :Text;
#    display @4 :Text;
#    fingerprint @5 :Text;
#    hardware @6 :Text;
#    host @7 :Text;
#    id @8 :Text;
#    manufacturer @9 :Text;
#    model @10 :Text;
#    product @11 :Text;
#    radioVersion @12 :Text;
#    serial @13 :Text;
#    supportedAbis @14 :List(Text);
#    tags @15 :Text;
#    time @16 :Int64;
#    type @17 :Text;
#    user @18 :Text;
#
#    versionCodename @19 :Text;
#    versionRelease @20 :Text;
#    versionSdk @21 :Int32;
#    versionSecurityPatch @22 :Text;
#  }
