# AndroidSensor Message

std_msgs/Int32 id
std_msgs/String name
std_msgs/String vendor
std_msgs/Int32 version
std_msgs/Int32 handle
std_msgs/Int32 type
std_msgs/Float32 maxRange
std_msgs/Float32 resolution
std_msgs/Float32 power
std_msgs/Int32 minDelay
std_msgs/UInt32 fifoReservedEventCount
std_msgs/UInt32 fifoMaxEventCount
std_msgs/String stringType
std_msgs/Int32 maxDelay



#  struct AndroidSensor {
#    id @0 :Int32;
#    name @1 :Text;
#    vendor @2 :Text;
#    version @3 :Int32;
#    handle @4 :Int32;
#    type @5 :Int32;
#    maxRange @6 :Float32;
#    resolution @7 :Float32;
#    power @8 :Float32;
#    minDelay @9 :Int32;
#    fifoReservedEventCount @10 :UInt32;
#    fifoMaxEventCount @11 :UInt32;
#    stringType @12 :Text;
#    maxDelay @13 :Int32;
#  }
