# ButtonEvent Message

std_msgs/Bool pressed
std_msgs/String type



#  struct ButtonEvent {
#    pressed @0 :Bool;
#    type @1 :Type;
#
#    enum Type {
#      unknown @0;
#      leftBlinker @1;
#      rightBlinker @2;
#      accelCruise @3;
#      decelCruise @4;
#      cancel @5;
#      altButton1 @6;
#      altButton2 @7;
#      altButton3 @8;
#      setCruise @9;
#      resumeCruise @10;
#      gapAdjustCruise @11;
#    }
#  }
