# Clock Message

std_msgs/Int64 timeNanos
std_msgs/Int32 hardwareClockDiscontinuityCount

std_msgs/Bool hasTimeUncertaintyNanos
std_msgs/Float64 timeUncertaintyNanos

std_msgs/Bool hasLeapSecond
std_msgs/Int32 leapSecond

std_msgs/Bool hasFullBiasNanos
std_msgs/Int64 fullBiasNanos

std_msgs/Bool hasBiasNanos
std_msgs/Float64 biasNanos

std_msgs/Bool hasBiasUncertaintyNanos
std_msgs/Float64 biasUncertaintyNanos

std_msgs/Bool hasDriftNanosPerSecond
std_msgs/Float64 driftNanosPerSecond

std_msgs/Bool hasDriftUncertaintyNanosPerSecond
std_msgs/Float64 driftUncertaintyNanosPerSecond
