# CPUTimes Message

std_msgs/Int64 cpuNum
std_msgs/Float32 user
std_msgs/Float32 nice
std_msgs/Float32 system
std_msgs/Float32 idle
std_msgs/Float32 iowait
std_msgs/Float32 irq
std_msgs/Float32 softirq



#  struct CPUTimes {
#    cpuNum @0 :Int64;
#    user @1 :Float32;
#    nice @2 :Float32;
#    system @3 :Float32;
#    idle @4 :Float32;
#    iowait @5 :Float32;
#    irq @6 :Float32;
#    softirq @7 :Float32;
#  }
