# LateralPIDState Message

std_msgs/Bool active
std_msgs/Float32 steerAngle
std_msgs/Float32 steerRate
std_msgs/Float32 angleError
std_msgs/Float32 p
std_msgs/Float32 i
std_msgs/Float32 f
std_msgs/Float32 output
std_msgs/Bool saturated



#  struct LateralPIDState {
#    active @0 :Bool;
#    steerAngle @1 :Float32;
#    steerRate @2 :Float32;
#    angleError @3 :Float32;
#    p @4 :Float32;
#    i @5 :Float32;
#    f @6 :Float32;
#    output @7 :Float32;
#    saturated @8 :Bool;
#   }
