# LateralINDIState Message

std_msgs/Bool active
std_msgs/Float32 steerAngle
std_msgs/Float32 steerRate
std_msgs/Float32 steerAccel
std_msgs/Float32 rateSetPoint
std_msgs/Float32 accelSetPoint
std_msgs/Float32 accelError
std_msgs/Float32 delayedOutput
std_msgs/Float32 delta
std_msgs/Float32 output
std_msgs/Bool saturated



#  struct LateralINDIState {
#    active @0 :Bool;
#    steerAngle @1 :Float32;
#    steerRate @2 :Float32;
#    steerAccel @3 :Float32;
#    rateSetPoint @4 :Float32;
#    accelSetPoint @5 :Float32;
#    accelError @6 :Float32;
#    delayedOutput @7 :Float32;
#    delta @8 :Float32;
#    output @9 :Float32;
#    saturated @10 :Bool;
#  }
