# LeadDataModel Message

std_msgs/Float32 dist
std_msgs/Float32 prob
std_msgs/Float32 std
std_msgs/Float32 relVel
std_msgs/Float32 relVelStd
std_msgs/Float32 relY
std_msgs/Float32 relYStd
std_msgs/Float32 relA
std_msgs/Float32 relAStd



#  struct LeadData {
#    dist @0 :Float32;
#    prob @1 :Float32;
#    std @2 :Float32;
#    relVel @3 :Float32;
#    relVelStd @4 :Float32;
#    relY @5 :Float32;
#    relYStd @6 :Float32;
#    relA @7 :Float32;
#    relAStd @8 :Float32;
#  }
