# LeadDataRadar Message

std_msgs/Float32 dRel
std_msgs/Float32 yRel
std_msgs/Float32 vRel
std_msgs/Float32 aRel
std_msgs/Float32 vLead
std_msgs/Float32 dPath
std_msgs/Float32 vLat
std_msgs/Float32 vLeadK
std_msgs/Float32 aLeadK
std_msgs/Bool fcw
std_msgs/Bool status
std_msgs/Float32 aLeadTau
std_msgs/Float32 modelProb
std_msgs/Bool radar




#  struct LeadData {
#    dRel @0 :Float32;
#    yRel @1 :Float32;
#    vRel @2 :Float32;
#    aRel @3 :Float32;
#    vLead @4 :Float32;
#    aLeadDEPRECATED @5 :Float32;
#    dPath @6 :Float32;
#    vLat @7 :Float32;
#    vLeadK @8 :Float32;
#    aLeadK @9 :Float32;
#    fcw @10 :Bool;
#    status @11 :Bool;
#    aLeadTau @12 :Float32;
#    modelProb @13 :Float32;
#    radar @14 :Bool;
#  }
