# LongitudinalPIDTuning Message

std_msgs/Float32[] kpBP
std_msgs/Float32[] kpV
std_msgs/Float32[] kiBP
std_msgs/Float32[] kiV
std_msgs/Float32[] deadzoneBP
std_msgs/Float32[] deadzoneV



#  struct LongitudinalPIDTuning {
#    kpBP @0 :List(Float32);
#    kpV @1 :List(Float32);
#    kiBP @2 :List(Float32);
#    kiV @3 :List(Float32);
#    deadzoneBP @4 :List(Float32);
#    deadzoneV @5 :List(Float32);
#  }
