# Mem Message

std_msgs/UInt64 total
std_msgs/UInt64 free
std_msgs/UInt64 available
std_msgs/UInt64 buffers
std_msgs/UInt64 cached
std_msgs/UInt64 active
std_msgs/UInt64 inactive
std_msgs/UInt64 shared



#  struct Mem {
#    total @0 :UInt64;
#    free @1 :UInt64;
#    available @2 :UInt64;
#    buffers @3 :UInt64;
#    cached @4 :UInt64;
#    active @5 :UInt64;
#    inactive @6 :UInt64;
#    shared @7 :UInt64;
#  }
