# MetaData Message

std_msgs/Float32 engagedProb
std_msgs/Float32[] desirePrediction
std_msgs/Float32 brakeDisengageProb
std_msgs/Float32 gasDisengageProb
std_msgs/Float32 steerOverrideProb
std_msgs/Float32[] desireState



#  struct MetaData {
#    engagedProb @0 :Float32;
#    desirePrediction @1 :List(Float32);
#    brakeDisengageProb @2 :Float32;
#    gasDisengageProb @3 :Float32;
#    steerOverrideProb @4 :Float32;
#    desireState @5 :List(Float32);
#  }
