# ModelSettings Message

std_msgs/UInt16 bigBoxX
std_msgs/UInt16 bigBoxY
std_msgs/UInt16 bigBoxWidth
std_msgs/UInt16 bigBoxHeight
std_msgs/Float32[] boxProjection
std_msgs/Float32[] yuvCorrection
std_msgs/Float32[] inputTransform



#  struct ModelSettings {
#    bigBoxX @0 :UInt16;
#    bigBoxY @1 :UInt16;
#    bigBoxWidth @2 :UInt16;
#    bigBoxHeight @3 :UInt16;
#    boxProjection @4 :List(Float32);
#    yuvCorrection @5 :List(Float32);
#    inputTransform @6 :List(Float32);
#  }
