# Process Message

std_msgs/Int32 pid
std_msgs/String name
std_msgs/UInt8 state
std_msgs/Int32 ppid

std_msgs/Float32 cpuUser
std_msgs/Float32 cpuSystem
std_msgs/Float32 cpuChildrenUser
std_msgs/Float32 cpuChildrenSystem
std_msgs/Int64 priority
std_msgs/Int32 nice
std_msgs/Int32 numThreads
std_msgs/Float64 startTime

std_msgs/UInt64 memVms
std_msgs/UInt64 memRss

std_msgs/Int32 processor

std_msgs/String[] cmdline
std_msgs/String[] exe
