# TrackingStatus Message

# pseudorange valid
std_msgs/Bool pseudorangeValid
# carrier phase valid
std_msgs/Bool carrierPhaseValid
# half cycle valid
std_msgs/Bool halfCycleValid
# half sycle subtracted from phase
std_msgs/Bool halfCycleSubtracted



#      struct TrackingStatus {
#        # pseudorange valid
#        pseudorangeValid @0 :Bool;
#        # carrier phase valid
#        carrierPhaseValid @1 :Bool;
#        # half cycle valid
#        halfCycleValid @2 :Bool;
#        # half sycle subtracted from phase
#        halfCycleSubtracted @3 :Bool;
#      }
